token:
  url: 'http://auth.mst.casicloud.com/1/token/create?client_id=4g0ucoqrwtn92dxq&ts=1528451123005&sign=ir834960bnjghze8343afajga'
  head: {"Content-Type": "application/json"}
  data: {
    "user_id": "10000041141535",
    "client_id": "4g0ucoqrwtn92dxq",
    "grant_type": "application_code",
    "scope": "app_scope"
  }

SupplierManagement:
  HOST: 'http://106.74.152.35:13249/'
  token:
    url: 'http://auth.mst.casicloud.com/1/token/create?client_id=4g0ucoqrwtn92dxq&sign=ir834960bnjghze8343afajga'
    head: {"Content-Type": "application/json"}
    data: {
      "user_id": "10000041141535",  #600633账号
      "client_id": "4g0ucoqrwtn92dxq",
      "grant_type": "application_code",
      "scope": "app_scope"
      }
  log:
    file_name: Supplier.log
    backup: 5
    console_level: INFO
    file_level: INFO
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

  mail:
    senduser: '676307573@qq.com'
    sendpswd: 'atcimddyfallbebb'
    receusers: ['676307573@qq.com']