token:
  Url: 'http://auth.mst.casicloud.com/1/token/create?client_id=4g0ucoqrwtn92dxq&sign=ir834960bnjghze8343afajga'
  url: 'http://auth.mst.casicloud.com/1/token/create?client_id=4g0ucoqrwtn92dxq&sign=ir834960bnjghze8343afajga'
  head: {"Content-Type": "application/json"}
  data: {
    "user_id": 10000041141535,
    "client_id": "4g0ucoqrwtn92dxq",
    "grant_type": "application_code",
    "scope": "app_scope"
  }

ETPSS:
  token:
    url: 'http://auth.mst.casicloud.com/1/token/create?client_id=4g0ucoqrwtn92dxq&sign=ir834960bnjghze8343afajga'
    head: {"Content-Type": "application/json"}
    data: {
      "user_id": 10000041141535,  #600633账号
      "client_id": "4g0ucoqrwtn92dxq",
      "grant_type": "application_code",
      "scope": "app_scope"
      }
  log:
    file_name: ETPSStest.log
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'